spring:
  profiles:
    active: default
logging:
  level:
    root: info

---

spring:
  profiles: dev
logging:
  level:
    root: info

---

spring:
  profiles: test
logging:
  level:
    root: info
  level.org.hibernate:
    SQL: debug
    type.descriptor.sql.BasicBinder: trace